### ISSUE TITLE
Draggable card lag when dragging

### ISSUE THREAD

**Issue by efremidze** [Yalantis/Koloda#80]
When dragging a card, if you let go there is a glitchy laggy effect. This happens on all iOS 9 devices.

**Comment by localsDeveloper** [comment]
I also see this issue. It's not smooth dragging. ThresholdMarginRatio does not change anything.
How did you solve it?

**Comment by efremidze** [comment]
I need to take a look. I don't remember how I fixed it.

**Comment by ndominati-luna** [comment]
I have the same issue. Can you have a look at it please? I really need it...
Thanks a lot in advance.

**Comment by localsDeveloper** [comment]
I still have this issue. Does anyone else get laggy dragging right before you release the card when swiping? I load data from backend (image and a few other properties) to fill the cards.
I wish to get a smooth dragging like in Readme.
